### ISSUE TITLE
Map conversions

### ISSUE THREAD

**Issue by marcosvidolin** [marcosvidolin/ditiow#29]
Add support for Map conversion

**Comment by akshitproothi** [comment]
I am a first time contributor, and I would like to contribute to this. How can I get started?

**Comment by marcosvidolin** [comment]
Hi @akshitproothi 

we don't have a map conversion so if a map has a Resource as a value **Ditiow** will not detect it.
This feature is very similar to the collection conversion. You can take a look at [assemblyMap](https://github.com/marcosvidolin/ditiow/blob/master/src/main/java/com/vidolima/ditiow/assembler/DomainAssembler.java) method.

Tks

**Comment by akshitproothi** [comment]
Ok thanks @marcosvidolin . Is there any setup guide i could follow to run and test this on my machine?

**Comment by marcosvidolin** [comment]
Hi @akshitproothi you can check the setup guide at README and run **./gradew test** to execute all tests from terminal

**Comment by akshitproothi** [comment]
Ok, thanks. Taking a look.

**Comment by akshitproothi** [comment]
@marcosvidolin Do you also want me to update the [getFieldGenericType](https://github.com/marcosvidolin/ditiow/blob/master/src/main/java/com/vidolima/ditiow/assembler/util/ReflectionUtil.java#L61) method?

I am unable to test my changes unless this method handles the value type of a map.

**Comment by akshitproothi** [comment]
Also, is [this](https://github.com/marcosvidolin/ditiow/blob/master/src/test/java/com/vidolima/ditiow/resource/PointResource.java#L7) supposed to be Address or Point as the type parameter?

**Comment by marcosvidolin** [comment]
> @marcosvidolin Do you also want me to update the [getFieldGenericType](https://github.com/marcosvidolin/ditiow/blob/master/src/main/java/com/vidolima/ditiow/assembler/util/ReflectionUtil.java#L61) method?
> 
> I am unable to test my changes unless this method handles the value type of a map.

Yeah, please.

**Comment by marcosvidolin** [comment]
> Also, is [this](https://github.com/marcosvidolin/ditiow/blob/master/src/test/java/com/vidolima/ditiow/resource/PointResource.java#L7) supposed to be Address or Point as the type parameter?

Address is the business entity so you need to inform Address as type. Is it right @ahmadmoawad ?

**Comment by akshitproothi** [comment]
One more thing @marcosvidolin @ahmadmoawad : In this [code](https://github.com/marcosvidolin/ditiow/blob/master/src/test/java/com/vidolima/ditiow/resource/UserGetResource.java#L20) , I noticed that the AddressResource is there but the list of points is not a List of PointResource but a List of Point . Shouldn't the UserGetResource only include subtypes of AbstractResource? The code [here](https://github.com/marcosvidolin/ditiow/blob/master/src/test/java/com/vidolima/ditiow/BaseTest.java#L63) used for the ResourceAssemblerTest doesn't populate that list either so it skips the test for that field (which would fail [here](https://github.com/marcosvidolin/ditiow/blob/master/src/main/java/com/vidolima/ditiow/assembler/ResourceAssembler.java#L41) because of type mismatch)

**Comment by akshitproothi** [comment]
Created a PR for the map conversion. Please let me know about the above questions i asked, and if you need me to make any changes related to those.

**Comment by marcosvidolin** [comment]
> One more thing @marcosvidolin @ahmadmoawad : In this code , I noticed that the AddressResource is there but the list of points is not a List of PointResource but a List of Point . Shouldn't the UserGetResource only include subtypes of AbstractResource? The code here used for the ResourceAssemblerTest doesn't populate that list either so it skips the test for that field (which would fail here because of type mismatch)

Yes, you are right! It should be an AbstractResource.

**Comment by marcosvidolin** [comment]
> Created a PR for the map conversion. Please let me know about the above questions i asked, and if you need me to make any changes related to those.

Thank you @akshitproothi for the improvements.
I'll review and merge it. 😎
